### PR TITLE
Added 'hyph' to prevent hyphenation (from McClass)

### PR DESCRIPTION
**Pull request by jeremyirilli**
-Unlike the original McClass-version, the left-element is not rendered in italics, so there is no difference between the two 't' in 't-test'.

-The 'mbox' in jax should  prevent hyphenation by putting the elements into a box

Source:   https://codeyarns.com/tech/2012-11-05-prevent-hyphenation-of-a-word-in-latex.html#gsc.tab=0

### CODE REVIEW

**Comment by mgondan** [comment]
Can you give a good example? I actually like _t_-test

**Comment by jeremyirilli** [comment]
The previous comment about the missing difference in font-styles was not meant to be interpreted as a decision I made, but rather as something which I had not managed to implement yet.
Now, with 'mi(L)' it should be rendered in italics.

**Comment by mgondan** [comment]
Maybe a misunderstanding on my side. What we need is:

In Prolog
hyph(t, "test") -> _t_-test (t in italics, because it is an atom)
hyph("t", "test") -> t-test (t in normal font, because it is a string)

In R
call("hyph", quote(t), "test") -> _t_-test
call("hyph", "t", "test") -> t-test

In other words, hyph should not influence the way in which the symbols left and right to the hyphen are being rendered. Can you confirm this?

**Comment by jeremyirilli** [comment]
Yes, the output is as expected, but in R with call("hyph", quote(t), "test") it just outputs hyph(t, "test") without evaluation.

image

**Comment by mgondan** [comment]
Fine, thank you.

**Pull request merged**
